master:
  restart: always
  image: eeacms/jenkins:master
  user: "1000"
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes_from:
    - data
  links:
    - postfix
  env_file:
    - master.env

worker:
  restart: always
  image: eeacms/jenkins:slave
  user: "1000"
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

docker:
  restart: always
  image: eeacms/jenkins:docker-slave
  user: "1000"
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/bin/docker

centos:
  image: eeacms/jenkins:centos-slave
  user: "1000"
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

debian:
  image: eeacms/jenkins:debian-slave
  user: "1000"
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

ubuntu:
  image: eeacms/jenkins:ubuntu-slave
  user: "1000"
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

postfix:
  restart: always
  image: eeacms/postfix
  env_file:
    - .secret
    - postfix.env
  volumes:
    - /etc/localtime:/etc/localtime:ro

data:
  build: data
  user: "1000"
  volumes:
    - /var/jenkins_home
