master:
  image: eeacms/jenkins:master
  restart: always
  user: "1000"
  ports:
  - "80:8080"
  - "50000:50000"
  volumes_from:
  - data
  links:
  - postfix
  env_file:
  - master.env

worker:
  image: eeacms/jenkins:slave
  restart: always
  user: "1000"
  volumes_from:
  - data
  env_file:
  - .secret
  - slave.env
  links:
  - postgres

postgres:
  image: eeacms/postgres
  restart: always
  env_file:
  - .secret

postfix:
  image: eeacms/postfix:eionet
  restart: always
  env_file:
  - .secret
  - postfix.env
  volumes:
  - /etc/localtime:/etc/localtime:ro

data:
  build: data
  user: "1000"
  volumes:
  - /var/jenkins_home:/var/jenkins_home/
